import 'dotenv/config'; import express from 'express'; import cors from 'cors'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { WebSocketServer, WebSocket } from 'ws';
import { loadState, saveState } from './store.js'; import { ObsControl } from './obs.js'; import type { AppState } from './types.js';
let state: AppState = loadState(); const app = express(); app.use(cors()); app.use(express.json()); const port = Number(process.env.PORT || 3010); const clients = new Set<WebSocket>();
function snapshot() { return { state, runtime: obs.runtime }; } function broadcast() { const message = JSON.stringify({ type: 'state', ...snapshot() }); clients.forEach(c => c.readyState === WebSocket.OPEN && c.send(message)); }
const obs = new ObsControl(broadcast); obs.configure(state.obs.url, state.obs.password); function initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map(x => x[0]?.toUpperCase()).join(''); }
app.get('/api/state', (_, res) => res.json(snapshot()));
app.get('/api/banner', (_, res) => res.json((state as AppState & { infoBanner?: { visible: boolean; headline: string; detail: string } }).infoBanner || { visible: false, headline: '', detail: '' }));
app.post('/api/banner', (req, res) => { const payload = req.body || {}; (state as AppState & { infoBanner?: { visible: boolean; headline: string; detail: string } }).infoBanner = { visible: Boolean(payload.visible), headline: String(payload.headline || ''), detail: String(payload.detail || '') }; saveState(state); broadcast(); res.json({ ok: true }); });
app.post('/api/action', async (req, res) => { const { action, payload = {} } = req.body; try {
  if (action === 'connect') { state.obs = { url: String(payload.url), password: String(payload.password || '') }; saveState(state); await obs.configure(state.obs.url, state.obs.password); }
  else if (action === 'refresh') await obs.refresh(); else if (action === 'program') await obs.setProgram(String(payload.scene)); else if (action === 'preview') await obs.setPreview(String(payload.scene)); else if (action === 'take') await obs.take(); else if (action === 'stream') await obs.toggleStream(); else if (action === 'record') await obs.toggleRecord(); else if (action === 'createScene') await obs.createScene(String(payload.name));
  else if (action === 'saveBranding') { state.branding = { ...state.branding, ...payload }; saveState(state); } else if (action === 'saveHotkeys') { state.hotkeys = payload.hotkeys; saveState(state); }
  else if (action === 'addPerson') { const name = String(payload.name || '').trim(); const role = String(payload.role || '').trim(); if (!name || !role) throw new Error('Name und Rolle sind erforderlich.'); state.people.push({ id: crypto.randomUUID(), name, role, company: String(payload.company || ''), color: String(payload.color || '#8059ff'), initials: initials(name) }); saveState(state); }
  else if (action === 'deletePerson') { state.people = state.people.filter(p => p.id !== payload.id); if (state.lowerThird?.id === payload.id) { state.lowerThird = null; state.lowerThirdVisible = false; } saveState(state); }
  else if (action === 'lowerThird') { const person = state.people.find(p => p.id === payload.personId); if (!person) throw new Error('Person nicht gefunden.'); state.lowerThird = person; state.lowerThirdVisible = true; saveState(state); }
  else if (action === 'hideLowerThird') { state.lowerThirdVisible = false; saveState(state); }
  else if (action === 'countdown') { state.countdown = { ...state.countdown, visible: Boolean(payload.visible), endsAt: payload.seconds ? Date.now() + Number(payload.seconds) * 1000 : state.countdown.endsAt, title: String(payload.title || state.countdown.title) }; saveState(state); }
  else if (action === 'addBrowserSource') { const base = String(payload.baseUrl || 'http://localhost:5173'); const kind = String(payload.kind); const name = kind === 'countdown' ? 'ONAIR Starting Soon' : kind === 'info-banner' ? 'ONAIR Info Banner' : 'ONAIR Lower Third'; const url = kind === 'info-banner' ? `${base}/overlay-info-banner.html` : `${base}/overlay/${kind}`; await obs.addBrowserSource(String(payload.scene), name, url, 1920, 1080); }
  else if (action === 'music') await obs.music(String(payload.input), payload.mediaAction);
  else throw new Error('Unbekannte Aktion.'); broadcast(); res.json({ ok: true, ...snapshot() });
} catch (e) { const message = e instanceof Error ? e.message : 'Action failed'; obs.runtime.lastError = message; broadcast(); res.status(400).json({ error: message }); } });
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'); app.use(express.static(path.join(root, 'public'))); app.use(express.static(path.join(root, 'dist'))); app.get('/{*splat}', (_, res) => res.sendFile(path.join(root, 'dist', 'index.html')));
const server = app.listen(port, () => console.log(`[OnAir] Control layer listening on :${port}`)); const wss = new WebSocketServer({ server, path: '/ws' }); wss.on('connection', ws => { clients.add(ws); ws.send(JSON.stringify({ type: 'state', ...snapshot() })); ws.on('close', () => clients.delete(ws)); });
